### ISSUE TITLE
"copy" will slide with the sliding bar（Chinese page and English page）

### ISSUE THREAD

**Issue by cbgz121** [Edgenesis/shifu.run#195]
![Snipaste_2022-11-28_14-18-03](https://user-images.githubusercontent.com/58777451/204208313-db20c795-9575-4451-94dc-909b79107fd1.png)
![Snipaste_2022-11-28_14-24-42](https://user-images.githubusercontent.com/58777451/204208338-aee4922b-16c2-41f7-abef-d3ccc3f9be71.png)

**Comment by 111fanyj** [comment]
https://github.com/Edgenesis/shifu.run/pull/203
and the place of "Copied successfully" is right after the pr
