### ISSUE TITLE
version not updated in Chinese page

### ISSUE THREAD

**Issue by cbgz121** [Edgenesis/shifu.run#196]
![Snipaste_2022-11-28_14-26-18](https://user-images.githubusercontent.com/58777451/204209078-46d4a1f8-b043-4366-a0ab-9d6092192a95.png)

**Comment by leepala** [comment]
Will modify the install url from github to gitee in Chinses?

**Comment by cbgz121** [comment]
> Will modify the install url from github to gitee in Chinese?

The current version is "0.5.0"

**Comment by cbgz121** [comment]
> Will modify the install url from github to gitee in Chinese?

![Snipaste_2022-11-28_14-38-14](https://user-images.githubusercontent.com/58777451/204210461-4f1d3065-87b4-4dda-adfa-c1c15ccc0cf9.png)

**Comment by cbgz121** [comment]
> Will modify the install url from github to gitee in Chinese?

like the english page
![Snipaste_2022-11-28_14-38-14](https://user-images.githubusercontent.com/58777451/204210552-0a4f7be3-1334-478c-bbba-5630fa0f793c.png)

**Comment by tomqin93** [comment]
fixed in https://github.com/Edgenesis/shifu.run/pull/199
