### ISSUE TITLE
Is it "使用"？

### ISSUE THREAD

**Issue by cbgz121** [Edgenesis/shifu.run#197]
![Snipaste_2022-11-28_14-33-11](https://user-images.githubusercontent.com/58777451/204210947-bed4994a-8bc2-4faf-bd85-59e49f1d7179.png)

**Comment by kris21he** [comment]
yes, please try PR and let's fix it

**Comment by cbgz121** [comment]
> yes, please try PR and let's fix it

OK，let me try pr
