### ISSUE TITLE
Is it "edgeDevice"?

### ISSUE THREAD

**Issue by cbgz121** [Edgenesis/shifu.run#198]
![Snipaste_2022-11-28_14-43-52](https://user-images.githubusercontent.com/58777451/204211305-2cb9d9e1-0e9b-4363-946e-a5348ba7181d.png)

**Comment by leepala** [comment]
yes, it's a typo

**Comment by kris21he** [comment]
next time you can mention the issue id in your PR and it will close this issue automatically
@cbgz121

**Comment by cbgz121** [comment]
> next time you can mention the issue id in your PR and it will close this issue automatically @cbgz121

ok
