### ISSUE TITLE
Production k8s can't install

### ISSUE THREAD

**Issue by fffguo** [Edgenesis/shifu.run#244]
https://shifu.dev/zh-Hans/docs/guides/install/install-shifu-prod

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/27751972/226508030-512112da-5c24-46a3-8015-82ab776652d1.png">

我找到了最新的yaml地址，但是还是无法安装
kubectl apply -f https://github.com/Edgenesis/shifu/blob/main/pkg/k8s/crd/install/shifu_install.yml
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/27751972/226508110-15f9c4b0-20d6-4153-a743-5bd10b7dba64.png">

**Comment by fffguo** [comment]
https://github.com/Edgenesis/shifu/blob/release_v0.14.0/pkg/k8s/crd/install/shifu_install.yml

最终我切换了分支，找到了最新的yaml

**Comment by fffguo** [comment]
<img width="1567" alt="image" src="https://user-images.githubusercontent.com/27751972/226509339-62748c45-ef11-4d6f-8846-4416ffcb1345.png">
但还是不行

**Comment by tomqin93** [comment]
Hi @fffguo, Thank you for creating this issue. We forgot to sync [Gitee](https://gitee.com/edgenesis/shifu) with our main GitHub repo. It is working now.
Just FYI, our main GitHub installation is guaranteed up to date.
Gitee:

```
kubectl apply -f https://gitee.com/edgenesis/shifu/raw/v0.14.0/pkg/k8s/crd/install/shifu_install.yml
```

GitHub:

```
kubectl apply -f https://raw.githubusercontent.com/Edgenesis/shifu/v0.14.0/pkg/k8s/crd/install/shifu_install.yml
```

**Comment by fffguo** [comment]
> https://gitee.com/edgenesis/shifu/raw/v0.14.0/pkg/k8s/crd/install/shifu_install.yml

感谢您的回复，使用gitee的yml配置解决了我的问题
